// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServiceApp.Database;

#nullable disable

namespace ServiceApp.Migrations.ServiceApp
{
    [DbContext(typeof(ServiceAppContext))]
    [Migration("20250624192603_One-To-Many")]
    partial class OneToMany
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ServiceApp.Database.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Jhon"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Den"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Tom"
                        },
                        new
                        {
                            Id = 4,
                            Name = "William"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Bob"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Sub-zero"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Scorpio"
                        },
                        new
                        {
                            Id = 8,
                            Name = "G.Freeman"
                        },
                        new
                        {
                            Id = 9,
                            Name = "G.Man"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Stevie"
                        });
                });

            modelBuilder.Entity("ServiceApp.Database.Models.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Devices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = 1,
                            Description = "Cell phone with 5G",
                            Name = "Iphone"
                        },
                        new
                        {
                            Id = 2,
                            ClientId = 1,
                            Description = "Laptop Lenovo",
                            Name = "ThinkBook 15"
                        },
                        new
                        {
                            Id = 3,
                            ClientId = 3,
                            Description = "SSD",
                            Name = "Samung 870 EVO"
                        },
                        new
                        {
                            Id = 4,
                            ClientId = 2,
                            Description = "Laptop HP",
                            Name = "HP ENVY 15"
                        },
                        new
                        {
                            Id = 5,
                            ClientId = 3,
                            Description = "Earphones, wireless",
                            Name = "Edifier 830"
                        });
                });

            modelBuilder.Entity("ServiceApp.Database.Models.Part", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("Parts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "n.a.",
                            DeviceId = 2,
                            Name = "main flex"
                        },
                        new
                        {
                            Id = 2,
                            Description = "for Iphone 6s",
                            DeviceId = 1,
                            Name = "battery Iph.6S"
                        },
                        new
                        {
                            Id = 3,
                            Description = "n.a.",
                            DeviceId = 1,
                            Name = "Main camera Iph.XS"
                        },
                        new
                        {
                            Id = 4,
                            Description = "n.a.",
                            DeviceId = 3,
                            Name = "Top case"
                        },
                        new
                        {
                            Id = 5,
                            Description = "n.a.",
                            DeviceId = 4,
                            Name = "Keyboard"
                        },
                        new
                        {
                            Id = 6,
                            Description = "n.a.",
                            DeviceId = 5,
                            Name = "Speaker"
                        },
                        new
                        {
                            Id = 7,
                            Description = "n.a.",
                            DeviceId = 4,
                            Name = "LCD flex"
                        });
                });

            modelBuilder.Entity("ServiceApp.Database.Models.Device", b =>
                {
                    b.HasOne("ServiceApp.Database.Models.Client", null)
                        .WithMany("Devices")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ServiceApp.Database.Models.Part", b =>
                {
                    b.HasOne("ServiceApp.Database.Models.Device", null)
                        .WithMany("Parts")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ServiceApp.Database.Models.Client", b =>
                {
                    b.Navigation("Devices");
                });

            modelBuilder.Entity("ServiceApp.Database.Models.Device", b =>
                {
                    b.Navigation("Parts");
                });
#pragma warning restore 612, 618
        }
    }
}
